# Generated by Django 4.0 on 2023-04-08 08:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Touristik_hudular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mavzu', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300)),
                ('Matn', models.TextField()),
                ('Rasm', models.ImageField(upload_to='hududlar/rasmlar')),
                ('chiqarilgan_vaqti', models.DateTimeField(default=django.utils.timezone.now)),
                ('yaratilgan_vaqti', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqti', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('TEK', 'Tekshirish'), ('CHQ', 'Chiqarish')], default='TEK', max_length=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tourism.category')),
            ],
            options={
                'ordering': ['-chiqarilgan_vaqti'],
            },
        ),
    ]
