# Generated by Django 4.0 on 2023-04-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='touristik_hudular',
            options={'ordering': ['yozilgan_vaqti']},
        ),
        migrations.RenameField(
            model_name='touristik_hudular',
            old_name='chiqarilgan_vaqti',
            new_name='yozilgan_vaqti',
        ),
        migrations.AlterField(
            model_name='touristik_hudular',
            name='status',
            field=models.CharField(choices=[('TEK', 'Tekshirish'), ('CHQ', 'Chiqarish')], default='TEK', max_length=20),
        ),
    ]
