# Generated by Django 4.0 on 2023-04-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0002_alter_touristik_hudular_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('xabar', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='touristik_hudular',
            options={'ordering': ['-yozilgan_vaqti']},
        ),
    ]
