# Generated by Django 4.0 on 2023-04-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0003_contact_alter_touristik_hudular_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacts',
        ),
    ]
