# Generated by Django 4.0 on 2023-04-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0004_rename_contact_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
