# Generated by Django 4.0 on 2023-04-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0005_rename_contacts_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristik_hudular',
            name='Rasm',
            field=models.ImageField(upload_to='media/hududlar/rasmlar'),
        ),
    ]
