# Generated by Django 4.0 on 2023-04-20 17:50

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0006_alter_touristik_hudular_rasm'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='touristik_hudular',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='touristik_hudular',
            name='Rasm',
            field=models.ImageField(upload_to='hududlar/rasmlar'),
        ),
    ]
