# Generated by Django 4.0 on 2023-04-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0007_alter_touristik_hudular_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viloyatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hudud', models.CharField(max_length=200)),
            ],
        ),
    ]
