# Generated by Django 4.0 on 2023-04-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0008_viloyatlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristik_hudular',
            name='korish_soni',
            field=models.IntegerField(default=0),
        ),
    ]
