# Generated by Django 4.0 on 2023-04-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0009_touristik_hudular_korish_soni'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Nomi_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Nomi_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Nomi_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='touristik_hudular',
            name='Matn_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='touristik_hudular',
            name='Matn_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='touristik_hudular',
            name='Matn_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='touristik_hudular',
            name='Mavzu_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='touristik_hudular',
            name='Mavzu_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='touristik_hudular',
            name='Mavzu_uz',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
